version: '3.8'


services:
  frontend:
    container_name: TypicalSchoolWebiste_Frontend
    build: 
      context: './TypicalSchoolWebiste_Frontend'
      dockerfile: Dockerfile
      args:
        #REACT_APP_API_URL: "http://localhost:${API_PORT_OUTSIDE}"  #container
        REACT_APP_API_URL: "http://localhost:8000"                  #local
    ports:
      - "3000:80"
    volumes:
      - '.:/app'
      - '/app/TypicalSchoolWebiste_Frontend/node_modules'
    networks:
      - frontendNetwork
    depends_on:
      - api


  api:
    container_name: TypicalSchoolWebsite_API
    build: 
      context: ./TypicalSchoolWebsite_API
      dockerfile: Dockerfile
      args:
        ASPNETCORE_EXPOSE_PORT: ${API_PORT_INSIDE}
    ports:
      - "${API_PORT_OUTSIDE}:${API_PORT_INSIDE}"
    environment:
      #Database
      DB_CONNECTION_STRING: "Host=TypicalSchoolWebsite_Database;Port=5432;Database=TSW_DB;Username=AdamDev;Password=TSW_PW"
      #JWT
      JwtKey: "This Is Very Secret Thing"
      JwtExpireTimeHours: "24"
      JwtIssuer: "Adam Informatyk"
      #Other
      ASPNETCORE_URLS: http://+:${API_PORT_INSIDE}
      #Services
      FILESTORAGESERVICE_URL: http://TypicalSchoolWebiste_FileStorageService:${FILESTORAGESERVICE_PORT_INSIDE}
      MODE: Production
    networks:
      - backendNetwork
    depends_on:
      - database
      - filestorageservice


  filestorageservice:
    container_name: TypicalSchoolWebiste_FileStorageService
    build: 
      context: ./TypicalSchoolWebsite_FileStorageService
      dockerfile: Dockerfile
      args:
        ASPNETCORE_EXPOSE_PORT: ${FILESTORAGESERVICE_PORT_INSIDE}
    ports:
      - "${FILESTORAGESERVICE_PORT_OUTSIDE}:${FILESTORAGESERVICE_PORT_INSIDE}"
    environment:
      ASPNETCORE_URLS: "http://+:${FILESTORAGESERVICE_PORT_INSIDE}"
    networks:
      - backendNetwork
    volumes:
      - TSW-FSS-volume:/app/FileStorage/Images

      
  database:
    container_name: TypicalSchoolWebsite_Database
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=AdamDev
      - POSTGRES_PASSWORD=TSW_PW
      - POSTGRES_DB=TSW_DB
    ports:
        - "56201:5432"
    networks:
      - backendNetwork
    volumes: 
        - TSW-db-volume:/var/lib/postgresql/data
        
volumes:
    TSW-db-volume:
    TSW-FSS-volume:

networks:
    frontendNetwork:
    backendNetwork:

