version: '3.7'


services:
  frontend:
    container_name: TypicalSchoolWebiste_Frontend
    build: 
      context: './TypicalSchoolWebiste_Frontend'
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:8000
    ports:
      - 3000:80
    volumes:
      - '.:/app'
      - '/app/TypicalSchoolWebiste_Frontend/node_modules'
    depends_on:
      - api

  api:
    container_name: TypicalSchoolWebsite_API
    build: 'TypicalSchoolWebsite_API'
    ports:
    - "8000:80"
    environment:
      #Database
      DB_CONNECTION_STRING: "Host=TypicalSchoolWebsite_Database;Port=5432;Database=TSW_DB;Username=AdamDev;Password=TSW_PW"
      #JWT
      JwtKey: "DockerJwtKey"
      JwtExpireTimeHours: "1"
      JwtIssuer: "Adam Informatyk"
      #Other
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - database
      
  database:
    container_name: TypicalSchoolWebsite_Database
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=AdamDev
      - POSTGRES_PASSWORD=TSW_PW
      - POSTGRES_DB=TSW_DB
    ports:
        - '56201:5432'
    volumes: 
        - db_volume:/var/lib/postgresql/data
        
volumes:
    db_volume:
#        external: true