version: '3.8'


services:
  frontend:
    container_name: TypicalSchoolWebiste_Frontend
    build: 
      context: './TypicalSchoolWebiste_Frontend'
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:${API_PORT_INSIDE}
    ports:
      - 3000:80
    volumes:
      - '.:/app'
      - '/app/TypicalSchoolWebiste_Frontend/node_modules'
    depends_on:
      - api


  api:
    container_name: TypicalSchoolWebsite_API
    build: 
      context: ./TypicalSchoolWebsite_API
      dockerfile: Dockerfile
      args:
        ASPNETCORE_EXPOSE_PORT: ${API_PORT_INSIDE}
    ports:
      - ${API_PORT_OUTSIDE}:${API_PORT_INSIDE}
    environment:
      #Database
      DB_CONNECTION_STRING: "Host=TypicalSchoolWebsite_Database;Port=5432;Database=TSW_DB;Username=AdamDev;Password=TSW_PW"
      #JWT
      JwtKey: "DockerJwtKey"
      JwtExpireTimeHours: "1"
      JwtIssuer: "Adam Informatyk"
      #Other
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:${API_PORT_INSIDE}
    depends_on:
      - database
      - fileStorageService


  fileStorageService:
    container_name: TypicalSchoolWebiste_FileStorageService
    build: 
      context: ./TypicalSchoolWebiste_FileStorageService
      dockerfile: Dockerfile
      args:
        ASPNETCORE_EXPOSE_PORT: ${FILESTORAGESERVICE_PORT_INSIDE}
    ports:
      - ${FILESTORAGESERVICE_PORT_INSIDE}:${FILESTORAGESERVICE_PORT_OUTSIDE}
    environment:
      ASPNETCORE_URLS: "http://+:${FILESTORAGESERVICE_PORT_INSIDE}"
    volumes:
      - TSW_fileStorageServiceVolume:/app/Storage/Images

      
  database:
    container_name: TypicalSchoolWebsite_Database
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=AdamDev
      - POSTGRES_PASSWORD=TSW_PW
      - POSTGRES_DB=TSW_DB
    ports:
        - '56201:5432'
    volumes: 
        - db_volume:/var/lib/postgresql/data
        
volumes:
    - db_volume
    - TSW_fileStorageServiceVolume
