apiVersion: v1
kind: Service
metadata:
  name: tsw-service
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: typicalschoolwebsite_frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsw-frontend-deployment
spec:
  selector:
    matchLabels:
      app: typicalschoolwebsite_frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: typicalschoolwebsite_frontend
        dude: "true"
    spec:
      containers:
      - name: frontend
        image: typicalschoolwebsite_frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 80
