apiVersion: v1
kind: Secret
metadata:
  name: tsw-api-secrets
type: Opaque
stringData:
  DB_CONNECTION_STRING: "Host=tsw-database-service;Port=30002;Database=TSW_DB;Username=AdamDev;Password=TSW_PW"
  JwtKey: "This Is Very Secret Thing"
  JwtExpireTimeHours: "24"
  JwtIssuer: "Adam Informatyk"
  ASPNETCORE_URLS: "http://+:2970"
  FILESTORAGESERVICE_URL: "http://+:2971"