version: '3.7'


services:
  api:
    container_name: TypicalSchoolWebsite_API
    build: 'TypicalSchoolWebsite_API'
    ports:
    - "8000:80"
    environment:
      DB_CONNECTION_STRING: "Host=postgresql_database;Port=5432;Database=TSW_DB;Username=AdamDev#;Password=typical_school_website_password#"
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/ 
    depends_on:
      - database
      
  database:
    container_name: TypicalSchoolWebsite_Database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "AdamDev#"
      POSTGRES_PASSWORD: "typical_school_website_password#"
      POSTGRES_DB: "TSW_DB"
    logging:
          options:
            max-size: 10m
            max-file: "3"
    ports:
        - '5438:5432'
    volumes: 
        - db_volume:/var/lib/postgresql/data
        
volumes:
  db_volume:
    external: true